/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/synthetic/regenerate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Regenerate */
        post: operations["regenerate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/drivers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Drivers */
        get: operations["list_drivers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/drivers/{driver_id}/schedule": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Driver Schedule */
        get: operations["driver_schedule"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/hubs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Hubs */
        get: operations["hubs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Jobs */
        get: operations["list_jobs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/jobs/{name}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger */
        post: operations["trigger"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Snapshots */
        get: operations["snapshots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Trips */
        get: operations["list_trips"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trips/{trip_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Trip */
        get: operations["get_trip"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vehicles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Vehicles */
        get: operations["list_vehicles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vehicles/{vehicle_id}/soc-checkin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Soc Checkin */
        post: operations["soc_checkin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Healthz */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Metrics */
        get: operations["metrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readyz */
        get: operations["readyz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** DriverOut */
        DriverOut: {
            /** Active */
            active: boolean;
            /** Approved Accounts */
            approved_accounts: string[];
            /**
             * Assigned Trips
             * @default 0
             */
            assigned_trips: number;
            /** Channel Today */
            channel_today: string;
            /**
             * Driver Id
             * Format: uuid
             */
            driver_id: string;
            /** End Lat */
            end_lat: number;
            /** End Lng */
            end_lng: number;
            /** Max Hours */
            max_hours: number;
            /** Name */
            name: string;
            /** Odometer Km */
            odometer_km?: number | null;
            /**
             * Service Date
             * Format: date
             */
            service_date: string;
            /** Shift End At */
            shift_end_at: string | null;
            /** Shift Start At */
            shift_start_at: string | null;
            /** Skills */
            skills: string[];
            /** Soc Pct */
            soc_pct?: number | null;
            /** Soc Reported At */
            soc_reported_at?: string | null;
            /** Start Lat */
            start_lat: number;
            /** Start Lng */
            start_lng: number;
            /** Vehicle Id */
            vehicle_id: string | null;
            /** Vehicle Model */
            vehicle_model?: string | null;
            /** Vehicle Registration */
            vehicle_registration?: string | null;
            /** Vehicle Status */
            vehicle_status?: string | null;
        };
        /** EstimateOut */
        EstimateOut: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Depart Bin */
            depart_bin: number;
            /** Distance M */
            distance_m: number;
            /** Expires At */
            expires_at: string | null;
            /** Kind */
            kind: string;
            /** P50 S */
            p50_s: number;
            /** P80 S */
            p80_s: number;
            /** P90 S */
            p90_s: number;
            /** Source */
            source: string;
        };
        /** EtaLogOut */
        EtaLogOut: {
            /** Actual S */
            actual_s: number;
            /**
             * Computed At
             * Format: date-time
             */
            computed_at: string;
            /** Covered P80 */
            covered_p80: boolean | null;
            /** Leg Kind */
            leg_kind: string;
            /** Predicted P50 S */
            predicted_p50_s: number | null;
            /** Predicted P80 S */
            predicted_p80_s: number | null;
            /** Residual Ratio */
            residual_ratio: number;
            /** Source */
            source: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HubOut */
        HubOut: {
            /** Ac Kw */
            ac_kw: number;
            /** Ac Points */
            ac_points: number;
            /** Dc Kw */
            dc_kw: number;
            /** Dc Points */
            dc_points: number;
            /**
             * Hub Id
             * Format: uuid
             */
            hub_id: string;
            /** Lat */
            lat: number;
            /** Lng */
            lng: number;
            /** Name */
            name: string;
        };
        /** JobInfo */
        JobInfo: {
            /** Default Date */
            default_date: string;
            /** Description */
            description: string;
            /** Name */
            name: string;
        };
        /** JobRunOut */
        JobRunOut: {
            /** Error */
            error: string | null;
            /** Finished At */
            finished_at: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Job Name */
            job_name: string;
            /** Service Date */
            service_date: string | null;
            /**
             * Started At
             * Format: date-time
             */
            started_at: string;
            /** Stats */
            stats: {
                [key: string]: unknown;
            };
            /** Status */
            status: string;
        };
        /** LoginIn */
        LoginIn: {
            /** Email */
            email: string;
            /** Password */
            password: string;
        };
        /** LoginOut */
        LoginOut: {
            /** Access Token */
            access_token: string;
            /** Email */
            email: string;
            /**
             * Expires At
             * Format: date-time
             */
            expires_at: string;
            /** Role */
            role: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** MeOut */
        MeOut: {
            /** Email */
            email: string;
            /** Role */
            role: string;
        };
        /** Page[JobRunOut] */
        Page_JobRunOut_: {
            /** Items */
            items: components["schemas"]["JobRunOut"][];
            /** Next Cursor */
            next_cursor?: string | null;
            /** Total */
            total?: number | null;
        };
        /** Page[TripRow] */
        Page_TripRow_: {
            /** Items */
            items: components["schemas"]["TripRow"][];
            /** Next Cursor */
            next_cursor?: string | null;
            /** Total */
            total?: number | null;
        };
        /** RegenerateAccepted */
        RegenerateAccepted: {
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
        };
        /** RegenerateIn */
        RegenerateIn: {
            /**
             * Days Future
             * @default 7
             */
            days_future: number;
            /**
             * Days Past
             * @default 45
             */
            days_past: number;
            /**
             * Seed
             * @default 42
             */
            seed: number;
        };
        /** RunAccepted */
        RunAccepted: {
            /** Job Name */
            job_name: string;
            /**
             * Run Id
             * Format: uuid
             */
            run_id: string;
            /** Service Date */
            service_date: string | null;
        };
        /** RunIn */
        RunIn: {
            /** Service Date */
            service_date?: string | null;
        };
        /** ScheduleOut */
        ScheduleOut: {
            /**
             * Driver Id
             * Format: uuid
             */
            driver_id: string;
            /** Plan Id */
            plan_id: string | null;
            /** Plan Version */
            plan_version: number | null;
            /** Published */
            published: boolean;
            /**
             * Service Date
             * Format: date
             */
            service_date: string;
            /** Stops */
            stops: components["schemas"]["ScheduleStop"][];
        };
        /** ScheduleStop */
        ScheduleStop: {
            /** Drop Address */
            drop_address: string;
            /** Locked */
            locked: boolean;
            /** Pickup Address */
            pickup_address: string;
            /** Planned Arrive Pickup At */
            planned_arrive_pickup_at: string | null;
            /** Planned Depart At */
            planned_depart_at: string | null;
            /** Planned Drop At */
            planned_drop_at: string | null;
            /** Planned Pickup At */
            planned_pickup_at: string | null;
            /** Seq */
            seq: number;
            /**
             * Trip Id
             * Format: uuid
             */
            trip_id: string;
            /** Trip Type */
            trip_type: string;
        };
        /** SnapshotOut */
        SnapshotOut: {
            /** Content Hash */
            content_hash: string;
            /** Counts */
            counts: {
                [key: string]: unknown;
            };
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Parent Snapshot Id */
            parent_snapshot_id: string | null;
            /** Reason */
            reason: string;
            /**
             * Service Date
             * Format: date
             */
            service_date: string;
            /**
             * Snapshot Id
             * Format: uuid
             */
            snapshot_id: string;
            /** Source */
            source: string;
        };
        /** SocCheckinIn */
        SocCheckinIn: {
            /** Driver Id */
            driver_id?: string | null;
            /** Odometer Km */
            odometer_km?: number | null;
            /** Service Date */
            service_date?: string | null;
            /** Soc Pct */
            soc_pct: number;
        };
        /** SocCheckinOut */
        SocCheckinOut: {
            /** Odometer Km */
            odometer_km: number | null;
            /**
             * Service Date
             * Format: date
             */
            service_date: string;
            /** Soc Pct */
            soc_pct: number;
            /**
             * Vehicle Id
             * Format: uuid
             */
            vehicle_id: string;
        };
        /** TripDetailOut */
        TripDetailOut: {
            /** Estimates */
            estimates: components["schemas"]["EstimateOut"][];
            /** Eta Log */
            eta_log: components["schemas"]["EtaLogOut"][];
            /** Lifecycle */
            lifecycle: {
                [key: string]: unknown;
            };
            /**
             * Snapshot Id
             * Format: uuid
             */
            snapshot_id: string;
            trip: components["schemas"]["TripRow"];
        };
        /** TripRow */
        TripRow: {
            /** Account Id */
            account_id: string | null;
            /** Actual Distance M */
            actual_distance_m: number | null;
            /** Actual Drop At */
            actual_drop_at: string | null;
            /** Actual Pickup At */
            actual_pickup_at: string | null;
            /** Channel */
            channel: string;
            /** Driver Id */
            driver_id?: string | null;
            /** Driver Name */
            driver_name?: string | null;
            /** Drop Address */
            drop_address: string;
            /** Drop Lat */
            drop_lat: number;
            /** Drop Lng */
            drop_lng: number;
            /** Estimate P50 S */
            estimate_p50_s?: number | null;
            /** Estimate P80 S */
            estimate_p80_s?: number | null;
            /** Estimate Source */
            estimate_source?: string | null;
            /**
             * Locked
             * @default false
             */
            locked: boolean;
            /** Luggage */
            luggage: number;
            /** Package Hours */
            package_hours: number | null;
            /** Pax */
            pax: number;
            /** Pickup Address */
            pickup_address: string;
            /** Pickup Lat */
            pickup_lat: number;
            /** Pickup Lng */
            pickup_lng: number;
            /** Planned Drop At */
            planned_drop_at?: string | null;
            /** Planned Pickup At */
            planned_pickup_at?: string | null;
            /**
             * Scheduled Pickup At
             * Format: date-time
             */
            scheduled_pickup_at: string;
            /**
             * Service Date
             * Format: date
             */
            service_date: string;
            /** Status */
            status: string;
            /** Tags */
            tags: {
                [key: string]: unknown;
            };
            /**
             * Trip Id
             * Format: uuid
             */
            trip_id: string;
            /** Trip Type */
            trip_type: string;
            /** Unassigned Reason */
            unassigned_reason?: string | null;
            /** Vehicle Class */
            vehicle_class: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** VehicleOut */
        VehicleOut: {
            /** Battery Kwh */
            battery_kwh: number;
            /** Driver Id */
            driver_id?: string | null;
            /** Driver Name */
            driver_name?: string | null;
            /** E Roll Wh Per Km */
            e_roll_wh_per_km: number;
            /** Hub Id */
            hub_id: string | null;
            /** Hub Name */
            hub_name?: string | null;
            /** Luggage Class */
            luggage_class: string;
            /** Model */
            model: string;
            /** Planning Cap Km */
            planning_cap_km: number;
            /** Registration */
            registration: string;
            /** Seats */
            seats: number;
            /** Soc Pct */
            soc_pct?: number | null;
            /** Status */
            status: string;
            /** Variant */
            variant: string;
            /** Vehicle Class */
            vehicle_class: string;
            /**
             * Vehicle Id
             * Format: uuid
             */
            vehicle_id: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    regenerate: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegenerateIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegenerateAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_drivers: {
        parameters: {
            query: {
                date: string;
                token?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DriverOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    driver_schedule: {
        parameters: {
            query: {
                date: string;
                token?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                driver_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScheduleOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    hubs: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HubOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobInfo"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs: {
        parameters: {
            query?: {
                name?: string | null;
                token?: string | null;
                limit?: number;
                cursor?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_JobRunOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobRunOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["RunIn"] | null;
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    snapshots: {
        parameters: {
            query?: {
                date?: string | null;
                token?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_trips: {
        parameters: {
            query: {
                date: string;
                q?: string | null;
                status?: string | null;
                token?: string | null;
                limit?: number;
                cursor?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_TripRow_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_trip: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                trip_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_vehicles: {
        parameters: {
            query?: {
                date?: string | null;
                token?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VehicleOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    soc_checkin: {
        parameters: {
            query?: {
                token?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                vehicle_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SocCheckinIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SocCheckinOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    metrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    readyz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
